[project]
name = "python-template"
version = "0.1.0"
description = "A python project template using uv"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "torch",
    "numpy",
]

[tool.hatch.build.targets.wheel]
packages = ["MalConv2-main"]
