# Binary-Hunter Configuration File

model:
  malconv:
    # MalConvGCT Model Hyperparameters
    channels: 256
    window_size: 256
    stride: 64
    embd_size: 8
    num_classes: 2

attack:
  # Adversarial Attack Settings
  # Padding length ratio relative to the original file size (0.01 = 1%)
  padding_ratio: 0.01
  
  # Number of optimization iterations (T)
  iterations: 20

explainability:
  deep_shap:
    # Baseline value for SHAP calculation
    # Options: 
    # - 'zero': Compare against all zeros (padding token)
    # - 'embedding_mean': Compare against the average of embedding vectors
    baseline: "zero"
    approximatioon: true
    